/**
 * This file contains utility types for working with the OpenAPI schema generated by openapi-typescript.
 * These types allow us to extract request and response types for specific API endpoints, ensuring that our API client
 * and other services that interact with the API are always in sync with the actual API schema.
 */

import type { paths as ApiPaths } from "@/services/api/generated/schema";

type OperationRequestBody<R> = {
	requestBody: R;
};

type OperationRequestBodyContent<R> = {
	content: { "application/json": R };
};

type RequestBody<Path extends keyof ApiPaths> =
	ApiPaths[Path]["post"] extends OperationRequestBody<infer RequestBody>
		? RequestBody extends OperationRequestBodyContent<infer Content>
			? Content
			: never
		: never;

type QueryParameters<Path extends keyof ApiPaths> = ApiPaths[Path]["get"] extends {
	parameters: infer Params;
}
	? Params extends { query: infer Q }
		? Q
		: never
	: never;

type OperationResponses<R> = {
	responses: R;
};

type OperationSuccessResponseContent<R> = {
	200: { content: { "application/json": R } };
};

type SuccessResponse<Path extends keyof ApiPaths, Verb extends keyof ApiPaths[Path]> =
	ApiPaths[Path][Verb] extends OperationResponses<infer Responses>
		? Responses extends OperationSuccessResponseContent<infer SuccessBody>
			? SuccessBody
			: never
		: never;

type SuccessQuery<Path extends keyof ApiPaths> = SuccessResponse<Path, "get">;
type SuccessCommand<Path extends keyof ApiPaths> = SuccessResponse<Path, "post">;

export type { QueryParameters, RequestBody, SuccessCommand, SuccessQuery, SuccessResponse };
